package com.zuikc.exception;

public class Demo6_Exception {

	public static void main(String[] args) throws AgeOutBoundsException  {
		Person p = new Person();
		p.setName("张三");
		p.setAge(-23);
		
		System.out.println(p.getName() + "..." + p.getAge());
	}

}
/*
 * * C:throws和throw的区别
	* a:throws
		* 用在方法声明后面，跟的是异常类名
		* 可以跟多个异常类名，用逗号隔开
		* 表示抛出异常，由该方法的调用者来处理
	* b:throw
		* 用在方法体内，跟的是异常对象名
		* 只能抛出一个异常对象名
		* 表示抛出异常，由方法体内的语句处理
 */
class Person {
	private String name;
	private int age;
	public Person() {
		super();
		// TODO Auto-generated constructor stub
	}
	public Person(String name, int age) {
		super();
		this.name = name;
		this.age = age;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public int getAge() {
		return age;
	}
	public void setAge(int age) throws AgeOutBoundsException  {
		if (age > 0 && age <200) {
			
			this.age = age;
		} else {
			throw new AgeOutBoundsException("非法年龄");
		}
	}
	
}